import { Inter } from 'next/font/google'
import './globals.css'
import Sidenav from './ui/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex flex-row h-screen selection:bg-black selection:text-white'>
          <div className='basis-3/12'><Sidenav/></div>
          <div className='basis-9/12'>{children}</div>
        </div>
      </body>
    </html>
  )
}
